#!/usr/bin/env bash
# 由 systemd timer 每天凌晨 3 点调用：让 codex 写一篇全新的、图文并茂的技术文章并发布。
# 约定与写作规则见仓库根目录 AGENTS.md。密钥从仓库外的 env 文件读取，绝不写进仓库。

set -uo pipefail

REPO_DIR="/home/fudongdong/blogs"
BRANCH="master"

# ---- 日志（仓库之外） ----
LOG_DIR="$HOME/.local/share/blog-autopost"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/run-$(date +%Y%m%d-%H%M%S).log"
exec >>"$LOG_FILE" 2>&1
echo "[ $(date '+%F %T') ] ==== blog auto-post start ===="

# ---- PATH：加载 nvm 的 node，并兜底显式加入 ----
export NVM_DIR="$HOME/.nvm"
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" >/dev/null 2>&1
export PATH="$HOME/.nvm/versions/node/v22.22.2/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# ---- 密钥（不在仓库内）：MINIMAX_API_KEY 等 ----
ENV_FILE="$HOME/.config/blog-autopost/env"
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
fi
if [ -z "${MINIMAX_API_KEY:-}" ]; then
  echo "ERROR: MINIMAX_API_KEY 未设置（应放在 $ENV_FILE）"; exit 1
fi

# ---- git 走 ssh，非交互 ----
export GIT_SSH_COMMAND="ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new"

cd "$REPO_DIR" || { echo "ERROR: 无法进入 $REPO_DIR"; exit 1; }

# 先同步远端，避免推送被拒
git pull --rebase origin "$BRANCH" || echo "WARN: git pull --rebase 失败，继续尝试"

# ---- 调用 codex 写文章（图文并茂、选新题材；不让它做 git 提交） ----
read -r -d '' PROMPT <<'EOF'
请先阅读本仓库根目录的 AGENTS.md 并严格遵守其中所有规则。

任务：写一篇【全新的、本仓库以前没有写过】的技术文章，并做到图文并茂：
1. 先读 source/_posts/ 下已有文章的标题，确保新主题不与任何已有文章重复。
2. 新建 source/_posts/<英文slug>.md，含完整 front-matter（title/date 用当前时间/tags/categories），正文 800-1500 字，结构清晰。
3. 用 .codex/skills/minimax-image/scripts/minimax_image.py 生成至少 1 张封面 + 1~2 张正文插图，
   全部存到 source/images/<slug>/ 下；提示词用英文、扁平/等距插画风、务必包含 "no text, no letters"。
   生成后用 file 命令确认每张都是有效 JPEG，坏图要换提示词重生成。
4. markdown 中引用站内图片用 /images/<slug>/xxx.jpeg（不要带 /blogs 前缀）。
5. 运行 npx hexo clean && npx hexo generate 确认构建无报错，并确认产物里没有 /blogs/blogs/ 这种双前缀。
6. 不要执行任何 git 提交或推送，交给外部脚本完成。
EOF

if ! codex exec --dangerously-bypass-approvals-and-sandbox -C "$REPO_DIR" "$PROMPT"; then
  echo "ERROR: codex exec 失败"; exit 1
fi

# ---- 自行再构建一次校验 ----
npx hexo clean >/dev/null 2>&1
if ! npx hexo generate; then
  echo "ERROR: hexo generate 失败，放弃发布"; exit 1
fi

# ---- 护栏：禁止双 /blogs/blogs 前缀（图片路径踩坑） ----
if grep -rq "/blogs/blogs/" public/ 2>/dev/null; then
  echo "ERROR: 产物中发现 /blogs/blogs/，图片路径有误，放弃发布"; exit 1
fi

# ---- 仅提交源码与图片（public、node_modules 已被 .gitignore 忽略） ----
git add -A
if git diff --cached --quiet; then
  echo "本次没有新增内容，跳过发布"
  echo "[ $(date '+%F %T') ] ==== done (no changes) ===="
  exit 0
fi

git commit -m "post: 自动生成技术文章 $(date '+%F')

Generated by codex via blog-autopost timer." || { echo "ERROR: commit 失败"; exit 1; }
git push origin "$BRANCH" || { echo "ERROR: push 失败"; exit 1; }

echo "[ $(date '+%F %T') ] ==== done (published) ===="
